### ISSUE TITLE
Use monthly AGCD data for cross correlation analysis

### ISSUE THREAD

**Issue by DamienIrving** [AusClimateService/npcp#14]
Step 1: @DamienIrving to pre-process the monthly data and make it available in `/g/data/ia39/npcp/data/pr/observations/AGCD/raw/task-reference/`.

Step 2: @AliciaTak to update `results/PT_cross_corr.ipynb`

**Comment by AliciaTak** [comment]
@DamienIrving Hi Damien, I was thinking about this issue as I am about to restructure the cross-correlation notebook. When we take monthly data for AGCD, we will change its characteristics as a reference. Because we would then compare the **resampled** cross-correlation of the models with the **un-resampled** cross-correlation of the reference, and we wouldn't be able to tell which portion of the changes are due to the cross-correlation and which due to resampling. What do you think?

**Comment by DamienIrving** [comment]
I guess another thing to consider is that our daily timescale bias corrected datasets (i.e. using the ECDFm, QME and QDM methods) was corrected against daily AGCD data. It would seem unfair / inappropriate to turn around and then assess them against a different observational dataset (i.e. AGCD monthly). Maybe we should stick with daily AGCD and close this issue?

**Comment by AliciaTak** [comment]
I agree. Closed!
